export const SLIDER_CONSTANTS = {
  DRAG_RESISTANCE: 0.4,
  SWIPE_THRESHOLD_PERCENT: 0.08,
  VELOCITY_THRESHOLD: 0.3,
  WHEEL_RESISTANCE: 0.3,
  WHEEL_SCROLL_THRESHOLD: 120,
  WHEEL_RESET_DELAY: 150,
  MOMENTUM_EASING: 0.1,
  ANIMATION_TIMEOUT: 800,
} as const

export const DEFAULT_COLORS = ["#1a1a2e", "#16213e", "#0f3460"] as const
